### ISSUE TITLE
Data Integrity in LibGit2Sharp

### ISSUE THREAD

**Issue by shubham140395** [libgit2/libgit2sharp#1388] opened 2016-11-17 10:15 UTC
Hello,
I am working on a project that uses LibGit2Sharp's Nuget package to clone the source code from github. I would like to get the technical details about the data integrity checks (If any?) that you people do. 

Thanks.

**Comment by ethomson** [comment] 2016-11-17 10:41
Hi @shubham140395 !

I'm not sure that I entirely understand the question.  You can read up on how Git handles integrity in [Pro Git](https://git-scm.com/book) and many other people have written about this on the internet, like http://www-cs-students.stanford.edu/~blynn/gitmagic/ch08.html.  (Googling "Git integrity check" should be enough.)

I'm closing this, since this is not a bug or feature request.  If you have questions about Git, libgit2 or LibGit2Sharp, we would encourage you to ask on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp), since that serves as an excellent question & answer site.

**Closed by ethomson** 2016-11-17 10:41 UTC

**Comment by shubham140395** [comment] 2016-11-17 10:58
Hi @ethomson 

I am a developer and I am using LibGit2Sharp packages to clone the repository code using repository.Clone method provided by LibGit2Sharp using c#. Can you please help me understand whether this method will make sure that it copies all the files and does not miss any files while cloning. Or is there a way I can check programmatically after cloning that I have received all files.

**Comment by txdv** [comment] 2016-11-17 13:02
libgit2 should ensure that everything is correct, if you want to do it on your own, you have to learn the git object format.

**Comment by whoisj** [comment] 2016-11-17 14:44
@shubham140395 have you looked at Git's structure, how it works, or anything?

I recommend doing so, this question is confusing to many here because Git's model effectively insures that tampering or having incomplete data is trivial to detect (good luck on getting two things to SHA to the same value while retaining meaningful value).

**Comment by shubham140395** [comment] 2016-11-18 09:15
Hi all,
I know about the Git's structure and how it works. What I mean by Data
integrity is that when I am doing a git clone, how do you ensure that all
the data is being transferred from the Source Control to the destination
location i.e No files are being missed(due to either network issues or any
other issues) and the content on both the source location and the
destination location is the same.

Also, if there are some issues due to which the entire data can't be cloned
to the destination location, does LibGit2Sharp takes care of that by
throwing error/exception.

Thanks and Regards,
Shubham Sharma

**Comment by shiftkey** [comment] 2016-11-18 13:47
Yes, you'll get an exception if the clone cannot complete successfully.

To verify the integrity of a repository after that, [`git fsck`](https://git-scm.com/docs/git-fsck) is the recommended approach. I haven't checked to see if it's supported in libgit2sharp.

**Comment by shubham140395** [comment] 2016-11-20 18:12
Are there any verifications done on your behalf once the clone is done
(successful or not) like SHA-1 check etc ?

**Comment by whoisj** [comment] 2016-11-21 15:14
This only take a tiny amount of research, the project is open-source.

LG2# invokes clone here: https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Core/Proxy.cs#L348

LG2's `git_clone` is here: https://github.com/libgit2/libgit2/blob/master/src/clone.c#L384 which effectively calls `git_remote_fetch` which you can look at here:https://github.com/libgit2/libgit2/blob/89c332e41b12a72d89de40d63bc568c56a2c336a/src/remote.c#L921; which basically relies on  git_remote_download blah blah blah

Ultimately it'll all come down the transport. With the HTTPS transport defined here: https://github.com/libgit2/libgit2/blob/89c332e41b12a72d89de40d63bc568c56a2c336a/src/transport.c#L21

Looking at the code, it appears no extra work is done to verify the integrity of the package (which I believe is the correct behavior). The callers should have the option to, and therefore be responsible for, validate the contents or not.

`git fsck` looks like a good friend.
