### ISSUE TITLE
Assess streaming filter support behavior in a memory constrained environment

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#1091] opened 2015-06-12 12:19 UTC
Considering this https://github.com/libgit2/libgit2sharp/pull/1030#issuecomment-111143524 and the comments below it, there are chances we may not play nice when the GC does its memory reclaiming duty.

It may interesting to test drive our implementation while the GC is running.

/cc @ammeep @shiftkey @ethomson @jamill @whoisj

**Comment by whoisj** [comment] 2015-06-12 15:38
While I have a very hard time believing that the CLR, especially on Windows where it is the most mature, would incorrectly over collect objects and thus result in `NullReferenceException` I suppose it wouldn't hurt to understand how intensive garbage collection impacts the library.

> It may interesting to test drive our implementation while the GC is running.

As I understand it, the GC is always running in the modern CLR. This allows it to be less impactful and helps to avoid the old "stuttering" that happened when the 1.0 CLR would suddenly decide to lock the object graph and start freeing memory.

I believe the real test here is how does the library perform under extreme memory pressure (example: 10 GB commit on a 8GB system).

Thoughts?

**Comment by carlosmn** [comment] 2015-06-12 15:50
It seems even odder that if the GC did collect some objects, their references would be set to `null` as that would mean the GC went and found those references and decided to set them to `null` even though it thought there were no references left to the object.

**Comment by ethomson** [comment] 2015-06-12 15:55
Yeah I'd also be a little bit surprised.  Usually those references dangle and some well-typed exception is thrown.

I'm curious what* is `null` when this error occurs?

**Comment by whoisj** [comment] 2015-06-12 15:56
> It seems even odder that if the GC did collect some objects, their references would be set to null as that would mean the GC went and found those references and decided to set them to null even though it thought there were no references left to the object.

My thoughts exactly. I'll try and ask Jared Par if that is even possible, but I highly doubt it is.

> I'm curious what* is null when this error occurs?

Me too. The reporting from the tests always accuse the first line of the test of being null. Perhaps it is a bug in xunit itself?

**Comment by whoisj** [comment] 2015-06-12 16:39
Jared got back to me, and no the GC will not collect any object which have references. He points us to look at potential issues with global state, which I think is completely reasonable.

The filters are registered globally, as in the loading of Libgit2, etc.

**Comment by ammeep** [comment] 2015-06-14 22:14
>He points us to look at potential issues with global state, which I think is completely reasonable.

One thing I have seen locally (when using test driven .net) is if the app domain is not torn down then any corrupted global state (from failing filter test runs) would naturally cause test failures on subsequent test runs.

I'm not familiar with exactly how app veyor works under the hood - does it tear down the entire app domain on each test run?

**Comment by nulltoken** [comment] 2015-06-15 07:20
> I'm not familiar with exactly how app veyor works under the hood - does it tear down the entire app domain on each test run?

AFAIK, each AppVeyor job (ie. build matrix entry) is run on a brand new blank machine instance.

**Comment by shiftkey** [comment] 2015-06-15 09:19
Would it be worth experimenting with [GC settings](http://stackoverflow.com/a/6005949/1363815) to see if we can get any sort of consistency on this?

Also, knowing *where* the NRE is occurring would be *amazing* right now... :sob:

**Comment by whoisj** [comment] 2015-06-15 15:27
Fiddling with my Exception settings, I've managed to collect some details on the NRE which keep occurring on a number of the write-to-disk tests.

> Test Name:	LibGit2Sharp.Tests.FilterFixture.CanFilterLargeFiles
Test Outcome:	Failed
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
Result StandardOutput:	
The directory 'X:\LibGit2Sharp-TestRepos\x4ez4qkq.zdu' could not be deleted (5 attempts were made) due to a System.IO.IOException: The process cannot access the file '09c4dc44-f22d-4b10-ad3e-23f0a527389c.blob' because it is being used by another process.
Most of the time, this is due to an external process accessing the files in the temporary repositories created during the test runs, and keeping a handle on the directory, thus preventing the deletion of those files.
Known and common causes include:
- Windows Search Indexer (go to the Indexing Options, in the Windows Control Panel, and exclude the bin folder of LibGit2Sharp.Tests)
- Antivirus (exclude the bin folder of LibGit2Sharp.Tests from the paths scanned by your real-time antivirus)
- TortoiseGit (change the 'Icon Overlays' settings, e.g., adding the bin folder of LibGit2Sharp.Tests to 'Exclude paths' and appending an '*' to exclude all subfolders as well)

Looks like something is keeping a lock on the temporary files, the clean up tasks are failing and throwing - thus causing the next test in line to fail with the blame.

I'm confirmed that Windows Search Indexer and my corporate prescribed Antivirus is excluding the local X:\ drive completely; and I do **not** have Tortoise anything installed. Thus I do not believe any of the suggested items are to blame.

Is it possible that something in the utfx is keeping a handle on files and blocking the clean up operations?

**Comment by ethomson** [comment] 2015-06-15 15:33
@whoisj Out of curiosity, what version of LibGit2Sharp are you seeing these problems with?

**Comment by nulltoken** [comment] 2015-06-15 15:34
When a folder cannot be deleted, this usually point at "A handle hasn't been properly released" cause. Would that be the case, as the leak detection mechanism hasn't cringed, it may mean that this handle hasn't been converted to a `SafeHandle` (but marshaled as an `IntPtr`).

Being compelled to force-quit TestDriven.net usually point at the same cause.

**Comment by whoisj** [comment] 2015-06-15 15:36
@ethomson top-of-tree (or very near the bleeding edge of vNext) as this is code I'm compiling and running local unit tests in Visual Studio.

@nulltoken there's code in the filter where `IntPtr` were used instead of `SafeHandle`s due to convenience. Do you think this is the issue (at least for the FilterFixture issues)?

**Comment by nulltoken** [comment] 2015-06-15 20:20
@whoisj How about opening a PR with the following changes:

 - Drop most of the time consuming tests (to keep the build as short as possible)
 - Decorate the Filter tests causing a NRE with some `Trace.Writeline()` calls (ie. à la `printf` debugging mode)
 - Wrap those tests in loops in order to raise the chance to see those failing

**Comment by whoisj** [comment] 2015-06-15 20:25
@nulltoken you may be a little crazy as you're thinking like me. :stuck_out_tongue_winking_eye:

I've already started down this path. I'll update with results ASAP.

**Comment by nulltoken** [comment] 2015-06-15 20:26
:stuck_out_tongue_closed_eyes: :bangbang:

**Comment by whoisj** [comment] 2015-06-15 21:37
@nulltoken assign this to me for now. If nothing else, it'll make finding the darn thing easier in the GH UX :wink:

**Comment by whoisj** [comment] 2015-06-19 15:38
Waiting on the results of #1107 to see if it can help narrow down some of the issues I'm seeing.

**Comment by carlosmn** [comment] 2015-06-19 18:13
Do you think then that the NRE comes from the cleanup functions rather than from anything inside the test? Though an NRE when we fail to delete a dir sounds bad, it'd be much better than it happening inside the filtering code.

**Comment by whoisj** [comment] 2015-06-19 20:10
> Do you think then that the NRE comes from the cleanup functions rather than from anything inside the test? Though an NRE when we fail to delete a dir sounds bad, it'd be much better than it happening inside the filtering code.

I do. The majority of the NRE are happening in the `DirectoryHelper.DeleteDirectory` as part of the `SelfCleaningDirectory` object's work.

**Comment by nulltoken** [comment] 2015-06-19 21:50
Strangely, I've never seen Travis choke on this. Only AppVeyor.

**Comment by whoisj** [comment] 2015-06-19 21:55
> Strangely, I've never seen Travis choke on this. Only AppVeyor.

Actually, that is true. Only AppVeyor and Visual Studio. :confused:

**Comment by whoisj** [comment] 2015-06-19 22:13
So now that I've got a more reliable way to repro this issue, here's the stack I see most frequently:

```
Test Name:	LibGit2Sharp.Tests.FilterFixture.WhenStagingFileApplyIsCalledWithCleanForCorrectPath
Test FullName:	LibGit2Sharp.Tests.FilterFixture.WhenStagingFileApplyIsCalledWithCleanForCorrectPath
Test Source:	C:\Src\LibGit2Sharp\LibGit2Sharp.Tests\FilterFixture.cs : line 118
Test Outcome:	Failed
Test Duration:	0:00:00.035

Result StackTrace:	
at LibGit2Sharp.Core.NativeMethods.git_index_add_bypath(IndexSafeHandle index, FilePath path)
   at LibGit2Sharp.Repository.AddToIndex(String relativePath) in C:\Src\LibGit2Sharp\LibGit2Sharp\Repository.cs:line 1999
   at LibGit2Sharp.Repository.Stage(IEnumerable`1 paths, StageOptions stageOptions) in C:\Src\LibGit2Sharp\LibGit2Sharp\Repository.cs:line 1745
   at LibGit2Sharp.Tests.FilterFixture.StageNewFile(IRepository repo, String contents) in C:\Src\LibGit2Sharp\LibGit2Sharp.Tests\FilterFixture.cs:line 352
   at LibGit2Sharp.Tests.FilterFixture.WhenStagingFileApplyIsCalledWithCleanForCorrectPath() in C:\Src\LibGit2Sharp\LibGit2Sharp.Tests\FilterFixture.cs:line 141
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

The test is failing at the call into Libgit2, which is super interesting because I would expect it to be failing at the `Ensure.ZeroResult(res);` call site immediately after. Perhaps it is and because I can only repro this in Release mode the line numbers are slightly off?

Right now I'm looking closely at the `Ensure` class. What is the expected result of asking libgit2 for its less error if there's no error logged?

**Comment by ethomson** [comment] 2015-06-19 23:05
If you're only seeing this on windows and never on Unix, it sounds like a file locking problem.

I don't really know the architecture, but I took a quick glance at `WriteStream.cs` and don't see you calling `close` on the `next` filter in the chain.  Is it possible that you're not closing the file you're writing?

**Comment by whoisj** [comment] 2015-06-19 23:15
Yeah the close call should be handled via this method:
```
        int StreamCloseCallback(IntPtr stream)
        {
            int result = 0;

            try
            {
                Ensure.ArgumentNotZeroIntPtr(stream, "stream");
                Ensure.ArgumentIsExpectedIntPtr(stream, thisPtr, "stream");

                using (BufferedStream outputBuffer = new BufferedStream(output, BufferSize))
                {
                    Complete(filterSource.Path, filterSource.Root, outputBuffer);
                }
            }
            catch (Exception exception)
            {
                Log.Write(LogLevel.Error, "Filter.StreamCloseCallback exception");
                Log.Write(LogLevel.Error, exception.ToString());
                Proxy.giterr_set_str(GitErrorCategory.Filter, exception);
                result = (int)GitErrorCode.Error;
            }

            result = nextStream.close(nextPtr);

            return result;
        }
```

**Comment by whoisj** [comment] 2015-06-23 18:24
I do believe I've a solid lead, finally.

```
Managed Debugging Assistant 'CallbackOnCollectedDelegate' has detected a problem in 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.exe'.

Additional information: A callback was made on a garbage collected delegate of type 'LibGit2Sharp!LibGit2Sharp.Core.GitFilter+git_filter_stream_fn::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.
```

It looks like, in many cases, we drop the reference to the filter object itself. What happens in that the GC cleans up the memory because it believes nothing is using it. The memory cleaned is the memory we've handed to native code (of course) and since it has been cleaned, native code causes an AV which is represented as a NRE in .NET.

Once one of these happens, other tests start failing in weird and spectacular ways. Looks like we end up corrupting memory when we do this. I'm looking to see if this is really caused by garbage collection or, more worrisome, memory compaction.

**Comment by nulltoken** [comment] 2015-06-23 19:26
Amazing :mag_right: job!

How you achieve troubleshooting this (*cough* asking for a friend *cough*)?

**Comment by whoisj** [comment] 2015-06-23 19:32
Yeah, I'll have a pull-request up shortly which seems to fix the issue in filters.

That said, I'm still getting random failure in other fixtures locally. I'm wondering if we're not doing the same thing in other places (scary thought).

**Comment by whoisj** [comment] 2015-06-23 21:04
Just pushed #1113 which appears to take care of the issue for filters.

I'm still seeing these issues in other fixtures, though nowhere near as frequently as they were seen in the filter fixture.

**Comment by whoisj** [comment] 2015-06-23 21:09
> How you achieve troubleshooting this (cough asking for a friend cough)?

Resilience. I just kept poking with everything I had at it. Visual Studio debuggger, Windbg, procman, etc. Eventually, I got a way to reproduce it with the VS debugger attached it was easy to find a resolution.

I think the most damning thing I did, was make the following comment:
>While I have a very hard time believing that the CLR, especially on Windows where it is the most mature, would incorrectly over collect objects and thus result in NullReferenceException I suppose it wouldn't hurt to understand how intensive garbage collection impacts the library.

Because, as it turns out, the GC can be collecting memory and causing this racy condition - but it's not the GC's fault - it was ours (mine).

**Comment by Therzok** [comment] 2015-06-24 08:37
By the way, you should also ensure the filter objects are pinned if they're long lived.

**Comment by whoisj** [comment] 2015-06-24 12:42
> By the way, you should also ensure the filter objects are pinned if they're long lived.

Good call!

**Comment by jamill** [comment] 2015-06-24 13:10
> Do we even need to worry about methods moving about during compaction?

We shouldn't have to worry about this.

**Comment by whoisj** [comment] 2015-06-24 13:18
> We shouldn't have to worry about this.

Ok, good. The more I thought about methods moving in memory, the more I started believing the CLR was doing amazing gymnastics keeping up with itself.

**Closed** 2015-06-30 22:06 UTC
Labels: Bug
