### ISSUE TITLE
Git clone returned 401

### ISSUE THREAD

**Issue by qianjin1** [libgit2/libgit2sharp#1439] opened 2017-04-21 13:32 UTC
I simply used method "Repository.Clone(string sourceUrl, string workdirPath, CloneOptions options)" to clone gerrit project via http protocol within CredentialsProvider set in options, and it throws 401 error.

`Repository.Clone(remotePath, localPath, new CloneOptions() 
{
    CredentialsProvider = (_url, _user, _cred) => new UsernamePasswordCredentials 
    {
        Username = "myUsername",
        Password = "myPassword" 
     }
});`

Does remote path not end with ".git" matters ? e.g. http://username@domain/project

**Comment by ethomson** [comment] 2017-05-05 17:13
> Does remote path not end with ".git" matters ?

You need to specify the URL that's given to you by the server administrator.  If it ends in `.git`, you should include it.  If it does not, you should not.  They should be able to help you understand why you're seeing permissions problem(s) when you clone.

I'm closing this since this is not a bug report - if you have questions about how to use LibGit2Sharp, we encourage you to ask on StackOverflow with the `libgit2sharp` tag.  Thanks!

**Closed by ethomson** 2017-05-05 17:13 UTC

**Comment by sankethpb** [comment] 2017-05-15 10:05
We are also facing this issue with latest version. Clone fails with 401 error.
The repository is hosted on a on premise gerrit server.
All permissions are available, and cloning it with "git clone http://xyz..." works fine.
