### ISSUE TITLE
Unable to load shared library 'git2-7ce88e6' or one of its dependencies.

### ISSUE THREAD

**Issue by Standret** [libgit2/libgit2sharp#1703] opened 2019-08-16 20:55 UTC
Hi there,

So I've encountered with a quite strange problem when I tried to run my program on ubuntu. As you can see in the log below the app crashes each time when trying to invoke any method from libgit, and it is quite strange cause this project works on Windows10 perfectly.

```
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
   at LibGit2Sharp.Core.NativeMethods.git_clone(git_repository*& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 275
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 779
   at Stt.GitSync.Infrastructure.Managers.RepositoriesManager.CloneIfNotExists(ConfigurationData data) in /home/grimm/Documents/SE/C#/SttGitSync/Stt.GitSync/Infrastructure/Managers/RepositoriesManager.cs:line 96

Unable to load shared library 'git2-7ce88e6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-7ce88e6: cannot open shared object file: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 78
   at LibGit2Sharp.Core.NativeMethods..cctor() in C:\projects\libgit2sharp\LibGit2Sharp\Core\NativeMethods.cs:line 56
```

### Reproduction steps
Try to use any LibGit2 method and you get this error

### Expected behavior
Repository is cloned

### Actual behavior
Exception is raised

### Version of LibGit2Sharp (release number or SHA1)
```
<PackageReference Include="LibGit2Sharp" Version="0.26.1" />
<PackageReference Include="LibGit2Sharp.NativeBinaries" Version="2.0.289" />
```

### Operating system(s) tested; .NET runtime tested
ubuntu 19.04
netcoreapp2.2

**Comment by montague247** [comment] 2019-08-18 09:23
Hi,

the same issue on my Mac.
10.14.5 (18F132) (Mojave)

On windows everything works fine.

Rolling back to 0.26.0 works.

Best regards

**Comment by Standret** [comment] 2019-08-20 18:44
Hmm, I've tried to create the empty project which just clones the public repository. and this error occurs again and again, and the version of libgit does not matter. I've also attached my .csproj, probably I've done something wrong.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.26.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="System.Reactive" Version="4.1.3" />
  </ItemGroup>

</Project>

```

**Comment by toanxyz** [comment] 2019-10-02 09:31
I have the same issue too when running in Azure Functions

**Comment by AleksandrSor** [comment] 2019-11-30 18:56
Apparently, lib2git cant find correct native binaries so I helped it with this trick
I had all needed binaries in /app/runtimes/ so i added env variable into my Dockerfile
like this

FROM base AS final

ENV LD_LIBRARY_PATH=/app/runtimes/debian.9-x64/native/

work for dotnet core 3.0 (aspnet:3.0-buster-slim)

**Comment by jayakumarj85** [comment] 2019-12-10 11:13
As of now libgit2sharp provides the native libraries for the following linux distributions,
win-x86           
win-x64           
win-arm64         
win               
unix              
ubuntu.18.04-x64  
ubuntu.16.04-arm64
rhel-x64          
osx               
linux-x64         
fedora-x64        
debian.9-x64      
debian-arm64      
alpine.3.9-x64    
alpine-x64        

In such case using ubuntu 19.04 is not going to work. Try using Ubuntu 18.04 and see if it works.

Otherwise try switching to any of the above mentioned linux distributions.

**Comment by matilote** [comment] 2019-12-18 13:07
`/root/.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9):` error : PlatformNotSupportedException: debian.9-arm64`
Tried different arm64 distributions with no luck.

**Comment by xJonathanLEI** [comment] 2019-12-31 17:24
Encountered the same issue when running in Docker. Changed my runtime from:

    FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

to

    FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic

solves the problem.

**Comment by nZeus** [comment] 2020-01-02 15:55
I tried `mcr.microsoft.com/dotnet/core/sdk:3.1-bionic` and it works! 🎉

**Comment by tanmay-18** [comment] 2020-02-10 13:44
> I tried `mcr.microsoft.com/dotnet/core/sdk:3.1-bionic` and it works! 🎉

How did you try this? Can you please explain? I am facing this problem in vsix project.

**Comment by paulostradioti** [comment] 2020-02-19 17:53
For me, it worked with mcr.microsoft.com/dotnet/core/sdk:3.1-alpine and mcr.microsoft.com/dotnet/core/runtime:3.1-alpine.

Thanks

**Comment by ahmedhammad97** [comment] 2020-02-29 22:27
Looks like the problem is that the binary `git2-7ce88e6` is built to the wrong directory, so the program is not able to load it when it look for it in the right one.

What worked for me was adding an [MSBuild](https://docs.microsoft.com/en-us/cpp/build/how-to-use-build-events-in-msbuild-projects?view=vs-2019) `PostBuildEvent` to `.csproj` which copies the `git2-7ce88e6` binary from the directory it was built, to the directory it is expected to run from.
These directories might differ, so it is better to check them manually.

**Comment by trondhindenes** [comment] 2020-03-14 17:48
> Try using Ubuntu 18.04

this is becoming a problem. Is there any plan to support newer ubuntu versions than 18.x?

**Comment by bording** [comment] 2020-03-14 21:23
> this is becoming a problem. Is there any plan to support newer ubuntu versions than 18.x?

It's not really sustainable to be constantly chasing support for newer platforms for a number of reasons. There needs to be a native binary compiled to match the versions of the dependencies on the distro.

There are plans to sidestep the entire problem by removing as many dependencies as possible from the native binary, enabling a single linux binary to work with most/all distros.

The biggest piece of work remaining to enable this is #1618.

**Comment by patrolez** [comment] 2020-03-31 02:21
Regarding newer Ubuntu:
https://github.com/libgit2/libgit2sharp/pull/1714#issuecomment-533828707

The most latest NuGet release `0.27-preview` works correctly.

**Comment by capraynor** [comment] 2020-04-26 07:04
Same issue here. This library won't work on Azure app service, Linux.
Doing the following settings can solve this issue: 
![image](https://user-images.githubusercontent.com/3467515/80300412-1647b680-87cf-11ea-8c62-bac21a873d89.png)

**Comment by tjmoore** [comment] 2020-09-04 16:35
Raspbian buster (Debian 10 based) has the same `Unable to load shared library 'git2-7ce88e6'`

I'm using [Nuke ](https://nuke.build/) to build and it's failing on [GitVersion](https://github.com/GitTools/GitVersion) which is using LibGit2Shap.

To be fair, building on a Raspberry Pi is not practical. Much better to cross compile for ARM. It was just curiosity really. Though it does mean I can't use GitVersion from the command line on the pi either. https://github.com/GitTools/GitVersion/issues/2260

**Comment by gitfool** [comment] 2020-09-06 04:17
@tjmoore I use [Cake](https://github.com/cake-build/cake) and [GitVersion](https://github.com/GitTools/GitVersion), which is a similar setup. You should be able to get it to work by pre-installing `GitVersion` and patching `LD_LIBRARY_PATH`, before calling `Nuke`, with a variant of @AleksandrSor's [workaround](https://github.com/libgit2/libgit2sharp/issues/1703#issuecomment-560011604).

See https://github.com/gitfool/Cake.Dungeon/commit/0655e23b94507896637f21d5636bfd8640542e75 for my workaround for the GitLab shared Linux runners which are now based on Debian 10.

**Comment by jessicah** [comment] 2020-11-02 03:10
Official .NET 5.0 Docker images are using Debian 10 now, so it'd be nice to see that added to the list of supported platforms. The LD_LIBRARY_PATH hack does work though...

**Comment by bigpod98** [comment] 2021-01-26 02:52
cmon fix this

**Comment by bording** [comment] 2021-01-26 04:25
@bigpod98 This should be fixed with the latest preview release.

**Comment by bigpod98** [comment] 2021-01-26 04:27
@bording after i vented my frustration i looked at other issues a bit closly and i found that i should use preview release and it worksy was just about to remove my frustrated comment

**Comment by bording** [comment] 2021-03-04 22:24
Since the latest preview release should have fixed this, I'm going to go ahead and close it.

**Closed by bording** 2021-03-04 22:24 UTC

**Comment by csurfleet** [comment] 2021-09-08 07:10
I'm on the latest preview (0.27.0-preview-0007) and this is not working on aspnet:5.0-buster-slim, which according to: https://hub.docker.com/_/microsoft-dotnet-aspnet is a debian 10 image. Could someone advise on the preview version/dotnet5 image combo I should be using please?

**Comment by bording** [comment] 2021-09-08 15:59
@csurfleet The latest preview version is 0.27.0-preview-0119, so give that a try.

**Comment by dradovic** [comment] 2021-09-23 15:14
@bording I'm experiencing the same problem with 0.27.0-preview-0119 on the Bitbucket CI/CD infrastructure. Unfortunately, it's not appearing consistently (I guess it depends what actual build agent is chosen to build the solution). The error I'm seeing is:

> System.TypeInitializationException : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
> ---- System.DllNotFoundException : Unable to load shared library 'git2-8a0dc67' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-8a0dc67: cannot open shared object file: No such file or directory

**Comment by aziz-shahed-cko** [comment] 2021-10-13 21:21
> libgit2sharp

Where can I find this list? 
I was able to make gitversion work using libssl1.1. But it does not work for Ubuntu 20.04.
If I could find the updated list for libgit2sharp , I could figure out which image I can use it with

**Comment by jayakumarj85** [comment] 2021-10-29 19:00
> 
> 
> > As of now libgit2sharp provides the native libraries for the following linux distributions, win-x86 win-x64 win-arm64 win unix ubuntu.18.04-x64 ubuntu.16.04-arm64 rhel-x64 osx linux-x64 fedora-x64 debian.9-x64 debian-arm64 alpine.3.9-x64 alpine-x64
> > In such case using ubuntu 19.04 is not going to work. Try using Ubuntu 18.04 and see if it works.
> > Otherwise try switching to any of the above mentioned linux distributions.
> 
> Where can I find this list? I was able to make gitversion work using libssl1.1. But it does not work for Ubuntu 20.04. If I could find the updated list for libgit2sharp , I could figure out which image I can use it with

Way back in 2019 when I posted this answer, I was using LibGit2Sharp.NativeBinaries v2.0.289 and libgit2sharp was providing the native libraries for the distributions I have mentioned. You can look at the list here under runtimes directory in the following link https://nuget.info/packages/LibGit2Sharp.NativeBinaries/2.0.289

The latest version of libgit2sharp v0.27.0-preview-0119 has a dependency on LibGit2Sharp.NativeBinaries v2.0.315-alpha.0.1, the native libraries supported can be found here https://nuget.info/packages/LibGit2Sharp.NativeBinaries/2.0.315-alpha.0.1

If you are using libgit2sharp v0.26.2, then it has a dependency on LibGit2Sharp.NativeBinaries v2.0.306, the native libraries supported can be found here https://nuget.info/packages/LibGit2Sharp.NativeBinaries/2.0.306

**Comment by Eternal21** [comment] 2022-12-25 23:09
Hitting the same problem trying to run LibGit2Sharp in AWS lambda

**Comment by MahdiKarimipour** [comment] 2023-02-06 02:58
> 0.27.0-preview

Upgrading to the preview fixed the _"Unable to load shared library 'git2-106a5f2' or one of its dependencies"_ 

As I was on alpine, it gave me another error that it is unable to load ssl/open ssl libraries, which I suspect is because alpine is lightweight. I switched to focal version and that fixed the ssl problem too.

**Comment by OskiKervinen-MF** [comment] 2023-02-14 08:21
I found a work around for this, when using the dotnet:sdk6.0-alpine image. I used strace to determine it was loading the library from `/app/runtimes/alpine.3.9-x64/native/libgit2-106a5f2.so`. So I installed libgit2 from apk and overrode that file with the system version. This is what it looks like in a `Dockerfile`:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine

RUN apk add git libgit2
COPY my_app/bin/Release/net6/publish/ /app/
RUN cp /usr/lib/libgit2.so.1.5 /app/runtimes/alpine.3.9-x64/native/libgit2-106a5f2.so
```

I would expect this sort of approach to work for any base image that can install a system libgit2, since the system libgit2 will be compatible with the system, while the native-managed invocations won't be tightly coupled, meaning the precise version of libgit2 isn't relevant to LibGit2Sharp, as long as all the entry points it calls are present.

**Comment by arrowd** [comment] 2025-06-02 12:34
I'm now building libgit2sharp on FreeBSD and also getting this error for obvious reason.

I'm actually surprised that libgit2sharp tries to ship all the possible variants of the native library rather than having an option to use (or at least to fallback to) a system libgit2.so coming from the OS package manager.
