### ISSUE TITLE
Move native binaries to "standard" directories

### ISSUE THREAD

**Issue by damageboy** [libgit2/libgit2sharp#1044] opened 2015-05-11 13:15 UTC
It seems that two other packages I'm using (For example, System.data.sqlite.org) are pushing their native binaries to the output path
under `x86` | `x64` folders, while libgit2sharp is pushing it into `NativeBinaries/amd64` | `NativeBinaries/x86`

It would be very nice if "everyone" could start standardizing on how to do native pre-loading...
Would it be acceptable to move to x86/x64 like the other packages are doing?

I'd be happy to contribute a pull-request cleaning this up...
I just wanted to ask nicely before coming out of the blue with a PR and explain my motivation for this.

**Comment by nulltoken** [comment] 2015-05-11 19:56
Thanks for putting this under the light!

To be honest, this isn't a subject that I've deeply studied and I didn't know there was some existing "standard' regarding in this area. Our folder structure (x86/amd64) took its inspiration from the SqlCe NuGet package format (initially published by @davidebbo).

I'm not against changing it, unless other contributors foresee some issues that this change could generate.

One thing I'm not sure about is how NuGet would handle the upgrade from a package with the current folder structure to the new proposed one. Would the old structure remain around? Would it be cleaned up?

@ethomson @jamill @bording Thoughts?

**Comment by bording** [comment] 2015-05-12 03:58
I've not really seen any standard in how other managed libraries handle native dependencies. For example, I know that the [ Microsoft.SqlServer.Types (Spatial)](https://www.nuget.org/packages/Microsoft.SqlServer.Types) uses a nativeBinaries folder like LibGit2Sharp does, but they go with x86/x64 instead of x86/amd64 for platform subfolders.

I can't think of a reason that there would be a problem caused by removing the NativeBinaries folder, especially considering that @ethomson recently added the ability to adjust the NativeLibraryPath.

>One thing I'm not sure about is how NuGet would handle the upgrade from a package with the current folder structure to the new proposed one. Would the old structure remain around? Would it be cleaned up?

NuGet doesn't really know anything about the folder structure, since we create all of that through msbuild magic via the props file. The old folder structure with the old binaries would end up sitting side by side with the new one. That same thing happens if the package gets removed, the binaries folder & files stick around because NuGet has no way to know to get rid of them.

I'd also need to update my packaging work to take this into consideration. Based on all of this, I'm not sure I see a benefit to making the change!

**Comment by ckuhn203** [comment] 2015-05-15 15:00
One thing to note is that this change may break people's build processes. For example, my build needs to copy the dll from the proper directory into the root `\bin\release\` directory depending on the bitness of the build. I'm not against the change, just calling out that this could be a kind of "breaking" change.

**Comment by nulltoken** [comment] 2015-06-11 12:21
@damageboy As a strong consensus doesn't seem to exist with regards to this proposal, I'm afraid this won't happen in the short term. 

Closing this for now, then. Feel free to comment and/or reopen this issue would a standard start to emerge.

Cheers!

**Closed by nulltoken** 2015-06-11 12:21 UTC
