### ISSUE TITLE
Invalid path: 'c:/dir/file.json'

### ISSUE THREAD

**Issue by Toppertje** [libgit2/libgit2sharp#1187] opened 2015-09-08 14:08 UTC
Hi,
I upgraded the NUGET package to the latest build to avoid the repo.clone error 'Invalid directory', but now I receive this error when a file is to be checked out. Is this a known bug?

Here are my statements:
string path = @"c:\bladiebla\";
Repository.Clone("https://gitent-location/project.git", path);

```
Stack:
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\projects\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 160
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in c:\projects\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 179
   at LibGit2Sharp.Core.Proxy.git_index_add_bypath(IndexSafeHandle index, FilePath path) in c:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 918
   at LibGit2Sharp.Index.Add(String pathInTheWorkdir) in c:\projects\libgit2sharp\LibGit2Sharp\Index.cs:line 196
   at ChecksTA._default.GitAddFiles(String path) in h:\DEV\VS2012\ChecksTA\ChecksTA\default.aspx.cs:line 120
   at ChecksTA._default.Button1_Click(Object sender, EventArgs e) in h:\DEV\VS2012\ChecksTA\ChecksTA\default.aspx.cs:line 45
```

The clone process starts now, the folder is created along with the metadata info, but file cannot be checked out.

Any ideas on this?

Regards,
Ronald

**Comment by ethomson** [comment] 2015-09-08 14:12
To be clear:  you have a file named `c:/dir/file.json` in your repository?

**Comment by carlosmn** [comment] 2015-09-08 14:18
You say you're performing a clone, but the stack refers to staging a file. Could you show what you *are* running when you hit the stack and what the exact path is that you're trying to stage? Is that path relative to the repository root or is it absolute?

**Comment by Toppertje** [comment] 2015-09-08 14:19
Hi Edward,

Yep, to be exact I have a repo named ‘sensu_checks_ta’, which contains sensu config files with names like ‘A2_Tunnel_GW.json’.

With git bash on the same box I can clone the repo, eg git clone https://github.schubergphilis.com/EETCust/sensu_checks_ta.git works.

Hope that helps, any info needed, let me know.

Grtz,
Ronald

**Comment by Toppertje** [comment] 2015-09-08 14:24
It’s an absolute path. Basically I just run:

            string path = @"E:\sensu_checks_ta";
            string httpsrepo = "https://github.schubergphilis.com/EETCust/sensu_checks_ta.git";
            if (Directory.Exists(path))
                Directory.Delete(path, true);
            Repository.Clone(httpsrepo, path);

Nothing more, nothing less. And on this point it throws an exception.
Path is definitely absolute.

**Comment by ethomson** [comment] 2015-09-08 14:26
What's the output of `git status` after you clone that with Git for Windows?

I'm asking not - do you have a resultant file named `c:/dir/index.json`, on your disk, after it's checked out.  I'm asking if you have checked in some file, into your repository, so that it's name is `c:/dir/index.json`.  *That's* the scenario that should cause that error message.

**Comment by Toppertje** [comment] 2015-09-08 14:31
I do not understand the point, because I clone it to an empty location? But here’s the output of git clone and git status.
It’s an existing repo with about 190 files.

a_rtop@EETMADM16V /e
$ git clone "https://github.schubergphilis.com/EETCust/sensu_checks_ta.git"
Cloning into 'sensu_checks_ta'...
remote: Counting objects: 20071, done.
remote: Compressing objects: 100% (13990/13990), done.
Receiving objects:  91% (18265/200remote: Total 20071 (delta 6035), reused 20059
(delta 6029), pack-reused 0
Receiving objects: 100% (20071/20071), 23.98 MiB | 16.32 MiB/s, done.
Resolving deltas: 100% (6035/6035), done.

a_rtop@EETMADM16V /e
$ git status
fatal: Not a git repository (or any of the parent directories): .git

a_rtop@EETMADM16V /e
$ cd sensu_checks_ta/

a_rtop@EETMADM16V /e/sensu_checks_ta (master)
$ git status
# On branch master
nothing to commit (working directory clean)

a_rtop@EETMADM16V /e/sensu_checks_ta (master)
$

**Comment by Toppertje** [comment] 2015-09-08 14:33
Should I do an git init before a repo.clone?

**Comment by ethomson** [comment] 2015-09-08 14:38
> I do not understand the point, because I clone it to an empty location?

No.  This has nothing to do with the path you're cloning into.

We're telling you that we believe that one of the filenames that is checked in to the repository that you're trying to clone is not valid and we cannot create it.  For example, you have a file named `.git`.  Or you have a file named `COM1`.  Or `C:`.

The surprising part is that Git for Windows does not similarly complain.

Is it possible for you to share the output of `git ls-files --stage` after cloning?

**Comment by Toppertje** [comment] 2015-09-08 14:40
But what I see is that the repo on local disk is populated, but still the error: ‘Invalid path: 'E:/_bla/A2_Tunnel_GW.json'’

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\projects\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 160
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in c:\projects\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 179
   at LibGit2Sharp.Core.Proxy.git_index_add_bypath(IndexSafeHandle index, FilePath path) in c:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 918
   at LibGit2Sharp.Index.Add(String pathInTheWorkdir) in c:\projects\libgit2sharp\LibGit2Sharp\Index.cs:line 196
   at ChecksTA._default.GitAddFiles(String path) in h:\DEV\VS2012\ChecksTA\ChecksTA\default.aspx.cs:line 122
   at ChecksTA._default.Button1_Click(Object sender, EventArgs e) in h:\DEV\VS2012\ChecksTA\ChecksTA\default.aspx.cs:line 45

But the file is there in the repo.
a_rtop@EETMADM16V ~
$ cd /e

a_rtop@EETMADM16V /e
$ cd _bla/

a_rtop@EETMADM16V /e/_bla (master)
$ git status
# On branch master
nothing to commit (working directory clean)

a_rtop@EETMADM16V /e/_bla (master)
$
a_rtop@EETMADM16V /e/_bla (master)
$ ls A2_Tunnel_GW.json
A2_Tunnel_GW.json

a_rtop@EETMADM16V /e/_bla (master)
$

**Comment by Toppertje** [comment] 2015-09-08 14:45
OK, I see, you suspect some kinda failure on the source. This is the output of git ls-files –-stage right after it’s cloned with git bash:
(BTW, is this info public or just shared between you and me?)

100644 11f026702a6fce8ad3250e9579c59947fca6b6ab 0  A2_Tunnel_GW.json
100644 9b04347d9546318480f48e67c176d80709694b18 0           AVR.json
100644 aeae375d300f9d99e09f3f1315e1653403c7fbe8 0   AVR_2e_LAN.json
100644 fc5bd9d315f2e152ca944b060451d8bbd8a6eb15 0 AVR_2e_LAN_GW.json
100644 9ca8eac7c81429b9c295c764c3639ae092909b76 0 AVR_GW.json
100644 f6a21548539bec2d5e949a957ec4aafb579ed250 0 AZN_Ziekenhuis_GW.json
100644 91b2cb34ba7b5efae2542a0b62a77d7c30cb7915 0            Acrres_GW.json
100644 e58a40cda2912dbebdeed4b7642f0b076a88f3e0 0          Afrikahaven_GW.json
100644 4cf0e5ab1a8c59fd84e3db76b8f1e2eb6da8730f 0  Anna_Vosdijk_GW.json
100644 f42719a137fd457e9e1f0705284d6c1446986c82 0   Arendonk_GW.json
100644 5afac4e712e065be864aad2e3e85a960362ca44b 0           Arlon_GW.json
100644 077c7fb65ef5a768a5a4e0f89071420f4c937b6e 0  Boswijk_GW.json
100644 76b3c75d4efa3f42f87468bf93c9dcde9059a279 0 Burnn_of_Whilk_GW.json
100644 e1ed16cb55bf94c968c7d7b8aa672e3ee516d937 0  CR_Plein_GW.json
100644 9a5f4292ebac65602b4c9d08d649b9c2d024a7b9 0          Centrale_MK.json
100644 959d6bb5b7a86603b2cb8a6f6fdf36182b4c9ae9 0 Centrale_MK_GW.json
100644 3b9a03a55d82c71ee4f6e02d9d1376e4d6e4b8c8 0            Ciney_GW.json
100644 6ad15325d5213b81f2728ac782eb0dfadf5bce0d 0  DP_Einde_net_meting3.json
100644 6b4a632755593173931ae79c73ade9ecfb8ec453 0 DP_Einde_net_meting4.json
100644 cdddb32e0ed2272c2ae5f36e831a5bb868b6e307 0           DP_Einde_net_meting_GW.json
100644 588813cb164c4082470abf1ccf54e3534ca6c392 0   DP_Einde_net_meting_GW2.json
100644 51acac171966a85235c74fa0a5bfe42c7d4e9958 0   DP_meting_t_b_v__WKC_Vathorst.json
100644 f5cbb093af66aa9e9056026f11941adb9f969a6c 0   DP_meting_t_b_v__WKC_Vathorst_GW.json
100644 44e5b54ff56db330c51a7bf7cd6536a05ee1c023 0 DeBras_GW.json
100644 a42b85164b117af557966f1f08e0c6e5994df074 0   De_Rotterdam_GW.json
100644 34cf9101aa72c1b38bc6f66810237976250fc9ff 0      Delfzijl_Noord_GW.json
100644 39046b548e382e60df90e594b3d3385e67fda614 0           Delfzijl_Noord_GW2.json
100644 ba975257aff8873866b779cbac1b0d856f17b895 0  Delfzijl_Noord_GW3.json
100644 6429c918a050ae5b83db1f59c4f57374a6e6c8bb 0 Delfzijl_Zuid_GW.json
100644 9afbe02c3fd3be225c123ae23abdaaa64d4f0f34 0 EFG.json
100644 72be4fea42728104befcfdc7fcdb2ec02674d499 0 EFG_GW.json
100644 2df10ad401411f3ac891854f5dec91389817a140 0      ES_MID.json
100644 8bfba5e4793ae181fdd46ad20afeed13261992bd 0  ES_MID_GW.json
100644 6b52ac6b674ddeac4d6ec180f482f3d9929bae0a 0            Eeklo_GW.json
100644 faf926dbbb763efc1037144a2f856a7a4f518c2c 0    Es_O.json
100644 4c90edf229a4a12cc52c8abca02a8ceecc90b784 0 Es_O_GW.json
100644 0863c6f60b87fc4b75c6ab247d3c0db908b15d4b 0           Faberlaan_GW.json
100644 ec0c5cf821b08842d671a2e5231291421643dc76 0   Fasc.json
100644 e50b5c5b15c4d747b9ce7047e9354c3906c28de7 0           Fasc_GW.json
100644 0f088c9595af5e14de06e8bfbdbc00599606c821 0 Fosses_la_Villes_GW.json
100644 1e27e6dad6516c5c87c3339dbd1919a57fec68a7 0   Fujifilm_GW.json
100644 66f4f2e2b46ae9c6bd5e64635b2a9b3222104c6a 0            Gouvy_GW.json
100644 cdda33f81546513fb97306d5b635c82cd6bbcee7 0 Grand_Manil_GW.json
100644 d5af0f1192d2acc7a92cf426947265ee6fa4e285 0   HC_3.json
100644 57299308df9a1b89cdece006a4cfc37008363ce0 0 HC_3_GW.json
100644 e7f0da891aa208777b2d3e8f8ce1e1315ffe4da7 0    HC_4.json
100644 5c9b2a19e717b6b1dcbad58e7c70eb7c903f2b2e 0 HC_4_GW.json
100644 5a18582123ed4958b6d0ea31d1c60ba736e6de41 0 HC_6.json
100644 5a17b3958ee703270f42d193a056f24552c77dca 0 HC_6_GW.json
100644 d4018ddc5c7cf4072d64ea68b0304c914c6f3f04 0 HWC_GW.json
100644 edba097c2f29b1b68cfb9dc1f8e20c6f2b8ed73b 0  Hartel_III_GW.json
100644 987889324b8205e5563c0b9081df8b95bd3325d7 0           Herkingen_GW.json
100644 e3ce2e1e51ea8c3b5b7b1d0edd4dadae601daacf 0 Hfdw.json
100644 8d465afd0504b8916aab3178981f5f2248bba902 0 Hfdw_GW.json
100644 132a9817492d05a0da1f10ac9a48c1960c2afabc 0    Hoevensche_Beemden_GW.json
100644 ebd4124297ab444eaa8f24347473fffcc4e63b89 0 Houten_GW.json
100644 7ddc8e0efd29fad796264510138235fa236f4a33 0  Kat.json
100644 525a97683362ea7f47681fd423b955d6f811002e 0  Kat_GW.json
100644 14fd35b82c02f3079900cbb3e8529358faf60513 0  Ketelhuis.json
100644 28ca87e813c71280a938bb823d7e6322c05cc483 0 Ketelhuis2.json
100644 e1bd81b5822a1f31d062666d2bc3dce161bf804d 0   Ketelhuis_GW.json
100644 1247db91cc51aea60f6c87b275cd2d8fe2b1a19d 0    Ketelhuis_GW2.json
100644 2a5c661cf9960f6bf2ea3353d4b6ef24bb126d36 0  Kral_Mb.json
100644 1c3e2eb84f42978484e7e2d357a466151992e074 0 Kral_Mb_GW.json
100644 44e240c4e4881dc6f31f16a86ec4c965e2c2fd7c 0   Kreekraksluis_GW.json
100644 54de28c59656c8f1a76b22ab02b56e110a8216ef 0   Laaksche_Vaart_GW.json
100644 d3bb5622de6d0622a84f745e4aa2260f224f2ac2 0           Laarakkerdijk_GW.json
100644 467358182062d913889e78cf033bf27b6f05c76d 0  Lochluichart_GW.json
100644 7ea6220a51e9cb7420a12687e06551678c52a8a6 0 Lopik_GW.json
100644 bee143fabe8aaee0c8a7977faf486c3dc48c9fbf 0   Luchterduinen_GW.json
100644 dc0687286c89252b47c9edb11f43488faa42b6fc 0  Maanplein_GW.json
100644 4624127b352dbaed6756e7ef8c2ab983f768f07d 0 Marbais_GW.json
100644 d7ed4b5b3e4b0191d194e8893c900dec2faab51b 0            Martina_Cornelia_GW.json
100644 f2a3a613e1ad56df67c95c9a25e6297ca494b774 0  Martina_Cornelia_GW2.json
100644 c0a712bc9c8564c33b9608395855887554001f75 0 Medemblikstr__GW.json
100644 b525ee1fef6d1c79f8e831c226bdeb35a6cb9369 0   Mobile_RTU_1_GW.json
100644 b8c70326745ff5959cf1de6ce0a15b5caba16dbb 0   Mobile_RTU_2_GW.json
100644 4dd1960930cf5b72a82714f4dce16417b5f8623f 0   Naaldwijksestr__GW.json
100644 31a14e6697db2fef7a94fb12f6fb9027e442dee8 0   Nes_NO.json
100644 e7a3b01bac2d5c75e439b4911d63ffd52248a88d 0 Nes_NO_GW.json
100644 d4b8bb6f2412992065fe7679b7aabac5fc1b9860 0 Nes_NW.json
100644 1f9a428e5777acbe2d03ddef05be90fdbe7d184f 0 Nes_NW_GW.json
100644 8bc161d9e7e6581aeb21e2c1a86e14297b25cd40 0   NieuweVeen_GW.json
100644 25e1813cc00e70305e6934e44a8fab3d034c1342 0 Nieuwegein_GW.json
100644 39732a031cf05e97830c6ad4f66845a46ecd7570 0 Ofl_IJs.json
100644 e8fe5f9de61ee933d8064b70cb3b6dbf20a3ac4c 0 Ofl_IJs_GW.json
100644 c82941fe427879ca24382b64428009b463583d83 0           Ofl_ZO.json
100644 481f0985edb578d88b932204a105b9a80d042d37 0          Ofl_ZO_GW.json
100644 feaa54a7fa075ad42c97ca7cea0d2fb14d425eb6 0 Omm_NO.json
100644 c7e4167311c1588b7db0ee52967b1cfb82057671 0    Omm_NO_GW.json
100644 97a030abed5537ea0da6367d0bfd1408fe78f663 0            Perwez_GW.json
100644 02c5cfe21274c6a3476097c9d0b31e18c4bdd5e3 0 Perwez_GW2.json
100644 75600e833c470befeccc244b232778092ebdb1c8 0           Piekketel_Keileweg_GW.json
100644 9163b8814f8a629098671d48bd278b44a17e9ac9 0 Pont_a_Celles_GW.json
100644 f6b66f8c7626f41f46ae5d448fde753e706165dd 0   Poptahof_GW.json
100644 f088763a09959c8fa24f006cfd4776745255acfd 0  Princes_Amalia_GW.json
100644 ddaf4b29d942dccfb90e078eb1fdc9880f412cd6 0 Provinciehuis_GW.json
100644 75e3c49b29d626b6fdcfa3c5f65f0ca41010dfed 0   Puurs_GW.json
100644 c0a614c123129ea2ecd4f437d417687cfd303d60 0  README.md
100644 ba520b93eb099c74592cbd6818acdb537c46a028 0          Rijswijkseweg_GW.json
100644 8246cd67d66519e63a0756357546fec3b649d047 0           RoCa.json
100644 374ff86481d9d62131a0e4daec3c00e9659abb1c 0  RoCa_GW.json
100644 e857c0cf0221c76829fa05be64f3d4ce980aeebb 0 Roc_Ev.json
100644 854b2c60494831505e7e732fa82097ab1af06323 0 Roc_Ev_GW.json
100644 e6a6088ff0e8b2fe27af7e491e3e5e1926b417c2 0    ST_CRO.json
100644 bad69cbb97da6cdae0cf8732d0c2d7dc0c56bba9 0          ST_CRO_GW.json
100644 a4fffee640ad2fe5a8240c06d4982cb2e6e15bd9 0 Sabinapolder_GW.json
100644 1798d319dcf2e58b590be1f4d319be7abb4c7079 0  Sch_NO.json
100644 399717bf276b8ef7250345cc89f70ca4f195c272 0    Sch_NO_GW.json
100644 215048fd41bb106532ee5938e5b627e0f2484357 0 Sch_ZO.json
100644 fda2f0aed26a0c05c39bed52ed2a9f2d0dc28c41 0 Sch_ZO_GW.json
100644 30e0ada6fbfb57e1b9128ecbfbe900d38329042b 0            Sch_ZW.json
100644 2ef63a21c46e4d44081a9cb27f17202a59dc09ed 0 Sch_ZW_GW.json
100644 410f52f71e1d86e1b82baa001bc94577e271ea81 0    Slufter_II_GW.json
100644 e6618d4db6de81096ea9c6a8fb539c6506c51428 0 SocialeZaken_GW.json
100644 e162b48a156997fa8388870cd6295d31cc20a3e0 0  Sombreffe_GW.json
100644 a99986d3b1a412e398481368e3e88b225ce65c43 0 StJanscollege_GW.json
100644 81ff30e933127d8c14cef7882ee42b47ea76fa77 0    St_Berg.json
100644 83adb2ad57128f08a2d8b88939b24924fb651209 0            St_Berg_GW.json
100644 16edf9d07289cfa0a474b6d96a9db3e73298f7a2 0 St_Blij.json
100644 a962c7613e64671ca8533e6f21c425f9040bc149 0   St_Blij_GW.json
100644 e698436de52d441be20c29406cd0a36da7679b25 0          St_Boez.json
100644 c8262d45e8aa67c16f9290dc661fe8fc965dd1a4 0   St_Boez_GW.json
100644 820fbc5ece1e1750cb81902025f361b50b290e4c 0  St_Del.json
100644 4f20f8fb8a864b3540a220303f834bd594eed1bd 0           St_Del_GW.json
100644 67764078e3e1bbfa6af39fa4e0221414d9417f04 0   St_Mar.json
100644 bc11a7ff2c2f796cacba833f2310100f3a8a9fb2 0       St_Mar_GW.json
100644 7f35c36a422fe99c5484355b244324651a3190bd 0 St_Rot.json
100644 a33b6c79ad6dd66b30608a00b9bfc49d328fe427 0          St_Rot_GW.json
100644 87271e22d0fec2b511d6ebfa3b66613385813fb9 0    St_Wdw.json
100644 605f325cd9f2558d8e3c49901ee2bf355b3b030f 0 St_Wdw_GW.json
100644 d98ae99818a1f85a5f871a9dcccd35321a57a19b 0     St__Antoinedijk_GW.json
100644 8527d3e06606d1b01a7d57a28dc55f8f5fce4773 0  Stadstuinen_1.json
100644 17cbc04a8066da513eb16eb155981dfa14ccb2b3 0   Stadstuinen_1_GW.json
100644 9b663dac67815fdb0fbb265f13be56d11101b04a 0   Stadstuinen_2.json
100644 288abbcb8ad10a7bb7d6d0bcf18a5f45c0444a94 0           Stadstuinen_2_GW.json
100644 3cc586bde16bfb0fe4c8fb1adec6f707364d3b59 0  T201_GW.json
100644 ad25620398dd8a262f0d03ea39a9fc7ca4aca0d8 0           T202_GW.json
100644 0109a1dbf6361f85fe944994cfa8f62a3d783c08 0    T203_GW.json
100644 14372a25c8fbe7ea735149d279aaa24a49f81271 0   T204_GW.json
100644 42d983cb77002ce7e8bccf8139d92324f0005386 0            T205_GW.json
100644 9aa36f2603de6e722cf65f36dafeb6e7cc6d6967 0  T206_GW.json
100644 beaf6267cdb100c4d301175ae8a3b8b9ce30d88a 0 T207_GW.json
100644 576219c28cb8228a96656d1a2a62f54f51df22c1 0     Tullo___Tullo_II_GW.json
100644 f54b5f8ac9d0554e64de6dda12ec1cce622ea3cb 0 Ver.json
100644 3263d728b9b86fb59a2ebd182a479a8a571fd08f 0 Ver_GW.json
100644 99d5e25bc0b835935a1f299a2d66c94e2e72511a 0  WFCC__oud_Haganum__GW.json
100644 c878871d9e6675f46d456639b4d6ed792e3dad51 0            WKC_Boterdorp_GW.json
100644 e857f6a19c3472e51835c60192fbbf96c957e5ba 0    WKC_GW.json
100644 267afa37dd3a4e5397b9c51be77e52b3d08a0a36 0           WKC_HWC_Ypenbug_GW.json
100644 e144c1e2ddcc2e9f463d85235f6fb034aa84b2f3 0  WKC_Harnaschpolder.json
100644 f3f9f881a716c1231d76dfcfe8b9e296185935a5 0       WKC_Harnaschpolder_GW.json
100644 c6f5d19da9c40462cfc936a49348695328e0899f 0  WKC_Oosterheem_GW.json
100644 d4493d5e9fb358309c9860d09ecda487d019dddc 0          WKC_Oostpolder_GW.json
100644 3701205518eae36d43417ab10097ec134daa6c1b 0  WKC_Vaanpark_GW.json
100644 883e9f3185f49c03be67de30b9682b83f6c04019 0 WKC_Vathorst_GW.json
100644 d9ca1538ce9a047116468098f17923b7d3b50455 0 WKC_Vijfwal_GW.json
100644 ebcbcb02ccee9a10c83847904c5f28748f8efe45 0  WKC_Wateringseveld_GW.json
100644 89a1b613a28aefaa53d561a71cf29d8b5e814332 0    WSG_EON.json
100644 b5060b542042b3f9b2cddacdafb550d1d7653c43 0          WSG_EON_2e_LAN.json
100644 070dce40823d2ed574e68523138177df03358d56 0           WSG_EON_2e_LAN_GW.json
100644 61de76cb2c288a2148850368ffba2e30a4846c56 0 WSG_EON_GW.json
100644 375638ed0b7dca506258c3af5f2602325d8be1bb 0            Waalwijk_GW.json
100644 126320ec0bf0f1c5a9b94785b849482487f0ec65 0 Warisoulx_GW.json
100644 aabc17163bf4bd2934e3613e3ace959b735f239f 0   Westenmeer_Wind_GW.json
100644 ed126b29b8f1a3cf6816a051a8ac16a4b2159c39 0     Weststad_III_GW.json
100644 eda320bef93324fe38d869ce3fe0cd21772d8151 0   Weststad_III___De_Locht_GW.json
100644 8cf9398125426d91f2de510ce1ac8e9af36b9707 0    ZP_Wilp.json
100644 272344f960db0f2b328d8ecafd78e47a0412a6e3 0            ZP_Wilp2.json
100644 89c3715fcf4a1e6be1cffc55a646a61544a0486b 0     ZP_Wilp_GW.json
100644 c31e1073fe38e869d2c004e474aa3d59f23d170b 0 ZP_Wilp_GW2.json
100644 bbb5132d651702adffd566b143e22aab889f9b4b 0 Zd_Hil.json
100644 3aad561a5a093d68663da71d13a8216e8842f8e6 0  Zd_Hil_GW.json
100644 e71ce9b16425cb6da9d493e0d0a8f900822508f1 0 Zpl_Ah.json
100644 8eb02ab46ccde6aec5879987b77b910be4957e21 0           Zpl_Ah_GW.json
100644 6301e1ef5d2eb0a32309395f77ec84d1f052879c 0   Zpl_Ik.json
100644 6af82c277a1c0fe88e71dd1e16cb1fa62c75737f 0      Zpl_Ik_GW.json
100644 741a024b8b04ecc1271370bc7c06557e75cc7353 0 Zvk_Mid.json
100644 92634ddd5ab949530f1b04762d26215677876233 0           Zvk_Mid_GW.json
100644 1b1394306a843d5195c4f1e48ef80d8390744b7a 0 Zvk_NO.json
100644 6bb259f1c82bf143c42ba131fb35d9ec6a0a1e8d 0    Zvk_NO_GW.json
100644 5246b25d9d9b97a17b67890e6d5d7b1192296b8d 0           Zvk_ZO.json
100644 59927335b37ccdbd5cb85b0796ac3659c3cf6cfd 0 Zvk_ZO_GW.json
100644 a894bbec2bc160658c37bcb5be1646fb0a0ec8f4 0 Zwartenbergseweg_GW.json
100644 21d0f0bf3810d894778e7c465c31eda6208dcd8e 0 ketelhuis_Amstelveen_GW.json
100644 cfae1f8872952264eb91084b681dd7fbecd2919b 0   template.txt
100644 8661124bbf9aa30ad3d3c2089a2226a7c30852da 0            van_Luna_GW.json
100644 2d03a67bff5709245790d84ffcfc3f7c4cb64cd1 0   van_Pallandt_GW.json

**Comment by Toppertje** [comment] 2015-09-08 14:50
Well, is this some async process? I have another function that stages files right after the clone statements. I commented out the stuff that is proceeding right after the clone, and now I get no errors …
Is there a time out?
And can you please let me know if our info is shared somewhere? If that is the case, I would to anonymize some stuff I sent

Grtz

**Comment by ethomson** [comment] 2015-09-08 14:51
Hm.  Thanks for this.  

This is shared publicly at this point, for the record - but it should contain only the filenames, not the contents.  If those are sensitive, you may wish to delete your comment (on GitHub).

**Comment by ethomson** [comment] 2015-09-08 14:55
Cloning is synchronous...  Are you quite certain that it's the `Repository.Clone` that's failing and not the subsequent staging?

**Comment by Toppertje** [comment] 2015-09-08 14:56
Just for your record, I am doing the following (single user app):
Delete dir
Repo.clone(dir)
DeleteFiles(*.json)
CreateNewFiles(All kinda json files)
GitAdd(*.json)
GitCommit
GitPush

Now, between Repo.clone(dir) and DeleteFiles(*.json) I put a thread.sleep(10000) and now it works.

So there is some kinda async there, I don’t know where, but if you have an event I can track, that would have my preference of course.

I ‘ll delete the senstitive stuff from Git, thanks for your quick help anyway.

Grtz

**Comment by Toppertje** [comment] 2015-09-08 15:00
Damn you are right, it's the staging. But why does that fail?

**Comment by ethomson** [comment] 2015-09-08 15:00
> So there is some kinda async there

There's really not, that would be very dangerous.  A repository instance is meant to be used by a single thread.  You cannot run adds on a repository object in parallel, or asynchronously.

**Comment by Toppertje** [comment] 2015-09-08 15:00
Yep, thought so

**Comment by Toppertje** [comment] 2015-09-08 15:01
OK, so why is the staging failing? The file does exist... ?

**Comment by Toppertje** [comment] 2015-09-08 15:14
Hi Edward,

I can use git bash to add a file, but doing the same from libgit2sharp fails on repo.index.add(file); git add file works

Any ideas?

regards

**Comment by carlosmn** [comment] 2015-09-08 15:15
Paths for staging are given relative to the repository root, not absolute to whatever system you're running. Do you have a file called `c:/dir/index.json` *inside* the repository path? If not, tell us what you are actually doing, otherwise it's all going to be guesswork.

If you're trying to stage a file inside a workdir, you must provide that path relative to the root of the workdir. Are you using the *exact same* path when you use git on the command line as you are passing to libgit2sharp?

**Comment by Toppertje** [comment] 2015-09-08 15:22
Ah, I add the absolute path here! Now I got the point of your first remark, do I have a file named c:\bla. Course not, but I tried to add the file with the full file path. Now I trimmed of the working dir and now it works!

Many thanks!

BTW, at first I used version 0.21, I upgraded to –Pre (NuGet Package Manager console). Any idea when 0.22 or even 0.23 will be released upon NuGet?

Grtz

**Comment by ethomson** [comment] 2015-09-08 15:46
Thanks for the update - since you've gotten this working, I'm going to close this.

I don't know if @nulltoken has a schedule for when he wants to release 0.22, but nuget packages will be part of that release - so as soon as 0.22 is tagged, there will be nuget packages available.

Thanks!

**Closed by ethomson** 2015-09-08 15:46 UTC

**Comment by nulltoken** [comment] 2015-09-08 18:30
@Toppertje `Stage` and `Unstage` accept relative paths. They also work with full rooted paths provided those lead to a file within the working directory.

If you're encountering an issue with this feature, please update this issue with a failing unit test or a small, self-contained piece of C# code that would allow us to reproduce your issue.

Cheers!
