### ISSUE TITLE
Error with LibGit2Sharp file

### ISSUE THREAD

**Issue by Vladimir-Goldenberg** [libgit2/libgit2sharp#1382] opened 2016-10-27 18:06 UTC
I try to install angular using bower.json file in VS 2015 comunity in Windows 10 and got the following problem:

   C:\WINDOWS\system32>git ls-remote --tags --heads https://github.com/angular/bower-angular.git

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'LibGit2Sharp, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.GitCli.GitShim.lsRemote(String url, Boolean headsOnly, Boolean tagsOnly)
   at Microsoft.VisualStudio.GitCli.Program.Main(String[] args)

This works perfectly in Windows 7

How can I fix this problem in windows 10

Thank you in advance for help!

Sincerely,
  Vladimir

**Comment by ethomson** [comment] 2016-10-27 18:16
I'm sorry, I'm not sure what you're asking exactly.  Are you using LibGit2Sharp?

It looks like some strange fake `git` has been installed on your system and it doesn't seem to work correctly.  It seems like _it_ uses LibGit2Sharp.

Is that true?  If so then I would recommend installing Git for Windows.

**Comment by Vladimir-Goldenberg** [comment] 2016-10-27 19:53
I created project on VS 2015 community and Windows 10. I should install angular (add line "angular":"1.5.8"  in bower.json file and add angular to project's library). When I try to update this file in windows 10 I've got this error during the instalation of angular on Visual studio. I do not have this problem on Windows 7

Sincerely,
  Vladimir

**Comment by ethomson** [comment] 2016-10-27 20:35
Right - I'm sorry, but this project is simply a dependency for VS 2015's bower installation.  We don't have anything to do with that.

Although the symptoms are different, I believe the solution is the same as:
http://stackoverflow.com/questions/28725727/vs-2015-bower-does-not-work-behind-firewall

Ultimately, please install Git for Windows instead of whatever fake git tool VS 2015 has provided which is obviously not working.

**Comment by Vladimir-Goldenberg** [comment] 2016-10-27 20:48
Thank you! I will try to solve this problem at home.
Sincerely,
  Vladimir

**Comment by ethomson** [comment] 2016-10-27 20:49
Please let me know if it works!

**Comment by Vladimir-Goldenberg** [comment] 2016-10-27 21:05
I created project on VS 2015 community and Windows 10. I should install angular (add line "angular":"1.5.8"  in bower.json file and add angular to project's library). When I try to update this file in windows 10 I've got this error during the instalation of angular on Visual studio. I do not have this problem on Windows 7


Sincerely,

  Vladimir


________________________________

**Comment by Vladimir-Goldenberg** [comment] 2016-10-30 22:13
Hi Edward!

    This problem still persists in my computer.  I registered this assembly to the GAC and VS 2015 stopped launching.  I tried to change url: git ls-remote --tags --heads https://github.com/angular/bower-angular-route.git but it does not help. I think there is problem referencing this file outside of my system. This problem persists only for installing packages related to angular ONLY. I was trying to install angular and angular-route packages and there is the same problem. So I solved this problem installing these packages using NuGet and referencing them  from other parts of my project outside of bower. Please let me know should you have any questions. You can use my system for debugging if you need.

Unfortunately, I forgot password for your website. This is a reason I am sending e-mail to you.

Sincerely,
  Vladimir
[https://avatars0.githubusercontent.com/u/139426?v=3&s=400]<https://github.com/angular/bower-angular-route.git>

angular/bower-angular-route<https://github.com/angular/bower-angular-route.git>
github.com
bower-angular-route - angular-route bower repo




________________________________

**Comment by ethomson** [comment] 2016-10-31 08:56
Please _do not_ install LibGit2Sharp into the GAC, that will not help you.

Like I said, the problem is with some piece of software that happens to use LibGit2Sharp.  It appears that Microsoft shipped this piece of software.  I would urge you to contact them, as we do not support software that was written using LibGit2Sharp, only LibGit2Sharp itself.

I would also urge you to make sure that you've updated the latest [Visual Studio 2015 Update 3](https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs) as often these sorts of bugs are fixed in the quarterly updates.

**Closed** 2016-11-20 09:25 UTC
