### ISSUE TITLE
Expose per line changes when diffing

### ISSUE THREAD

**Issue by adamveld12** [libgit2/libgit2sharp#1159] opened 2015-07-23 16:49 UTC
I would like to be able to build my own diff output, and see line by line changes (with additions and deletions) and it seems like that functionality isn't available as of yet.

I searched around and didn't find any examples of this being done, but I did notice that `git_diff_blobs()` is in the `NativeMethods.cs` and this would put me on the right track to giving me what I'd want.

**Comment by Therzok** [comment] 2015-07-23 20:34
Possible dupe of #1142

**Comment by nulltoken** [comment] 2015-09-17 20:01
@Therzok Looks like so, indeed.

**Closed by nulltoken** 2015-09-17 20:01 UTC
