### ISSUE TITLE
Patch line changes

### ISSUE THREAD

**Issue by Aghlara** [libgit2/libgit2sharp#1189] opened 2015-09-17 06:44 UTC
Hi,

I use 
```
 Patch changes = repo.Diff.Compare<Patch>(rootCommitTree, commitTreeWithUpdatedFile);
```

To get a patch between two tree, that only shows numbers for LinesAdded and LinesDelete. How can I iterate on those lines?
I want to use ScintillaNet and build text and highlight the lines that are added and deleted.

Any solution for this?

Regards,

**Comment by Aghlara** [comment] 2015-09-17 06:48
Want to build something like this:

![image](https://cloud.githubusercontent.com/assets/5187409/9926788/e3ac05de-5d5b-11e5-84f7-051e17b81645.png)

**Comment by nulltoken** [comment] 2015-09-17 19:58
As stated in the **[README](https://github.com/libgit2/libgit2sharp#troubleshooting-and-support)**, we tend to keep the issue tracker for bug and feature related topics. 

Would you be so kind as to ask this on **[StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp)** and decorate your question with the `libgit2sharp` tag? We'll gladly answer you over there.

Cheers!

**Comment by Therzok** [comment] 2015-09-17 19:59
Also, kinda dupe of https://github.com/libgit2/libgit2sharp/issues/1142

**Closed by nulltoken** 2015-09-17 19:58 UTC
