### ISSUE TITLE
Issue using commit filter.

### ISSUE THREAD

**Issue by pavlearezina** [libgit2/libgit2sharp#1536] opened 2018-02-26 18:48 UTC
Hello,

I am stuck using the commit filter.
Always getting the message in screen shot
![error](https://user-images.githubusercontent.com/15236969/36688812-95b5fb72-1afb-11e8-9e33-8ffe1b7e8de3.PNG)

Not sure if I setup anything incorrectly. Any help is appreciated.

**Comment by ethomson** [comment] 2018-02-26 19:02
Hello @pavlearezina.  You can see from the exception that the problem is not the `CommitFilter`, it's that `repo.Lookup<Commit>(lastHash)` returned `null` and you are trying to dereference it.

**Comment by ethomson** [comment] 2018-02-26 19:03
For questions about API usage, we would encourage you to use [StackOverflow](https://stackoverflow.com/questions/tagged/libgit2sharp) for a number of reasons:  it's much higher traffic and thus higher visibility, it's searchable and historic, and it allows us to keep issues like bugs and features in the issue tracker.

I'm going to close this issue - if you have other questions, please open a question on StackOverflow and we'll help you there.  Thanks!

**Closed by ethomson** 2018-02-26 19:03 UTC
