### ISSUE TITLE
Native dlls copied to the bin folder on build

### ISSUE THREAD

**Issue by uluhonolulu** [libgit2/libgit2sharp#1089] opened 2015-06-10 18:36 UTC
Recent libgit2sharp Nuget uses a new Nuget feature that allows you to include a piece of a build script in your NuGet. 

It worked great on my dev machine, but when I deployed it to AppHarbor, the native dlls appeared in the /bin folder (in addition to the target subfolder), which caused my app to fail.

The problem lies in the `_CopyWebApplicationLegacy` target, which does not execute locally (it's run only if you have a non-default output dir), thus I don't have this problem on my dev machine. Namely, it executes the following piece of code:

```
<!-- Copy items that have been marked to be copied to the bin folder -->
<Copy SourceFiles="@(_SourceItemsToCopyToOutputDirectory)" 
      DestinationFolder="$(WebProjectOutputDir)\bin" 
      SkipUnchangedFiles="true" 
      Retries="$(CopyRetryCount)"
      RetryDelayMilliseconds="$(CopyRetryDelayMilliseconds)"/>
```
You can see that the target folder is always /bin -- I believe it's a bug in the Microsoft.WebApplication.targets file (I can't control it on the target machine).

I had to fix it by adding a postbuild task that removed the files from the bin folder.

**Comment by nulltoken** [comment] 2015-06-10 19:01
Related **[StackOverflow question](https://stackoverflow.com/questions/30685552/binary-files-copied-to-a-wrong-folder-on-build#comment49431503_30685552)**

@bording some of your voodoo magic may be *very* helpful here :pray:

**Comment by bording** [comment] 2015-06-10 19:10
I was just looking at this!

The trick is going to be finding out how `@(_SourceItemsToCopyToOutputDirectory)` is built up and seeing if there is some way to make sure the native binaries are excluded.

I'll see what I can come up with.

**Comment by bording** [comment] 2015-06-10 19:18
@uluhonolulu Just to clarify, you're saying that you're seeing the native git2.dll show up in bin\NativeBinaries and bin?

So, both `bin\NativeBinaries\amd64\git2-ff8d635.dll` and `bin\git2-ff8d635.dll` ?

**Comment by bording** [comment] 2015-06-11 05:15
So, I spent some time looking into this and got a local repro, and it's not really anything wrong with LibGit2Sharp or the props file it uses.

The problem comes from how AppHarbor is calling msbuild. According to their **[FAQ](https://support.appharbor.com/kb/getting-started/frequently-asked-questions/)** they call the followint: `msbuild solution.sln /p:Configuration=Release /property:OutDir=C:\temp`

By messing with the OutDIr property, that is what is triggering the _CopyWebApplicationLegacy target from running, and that's what the problem is. That really shouldn't be used any more, because it has all sorts of problems, including the messed up copying behavior @uluhonolulu is seeing. Any items in a project that use the Copy to Output Directory property will be broken, regardless of how they got into the project. It also doesn't run any web.config transforms in the project.

The _CopyWebApplication target that has replaced the Legacy version appears to work properly, and you can use that one instead with a couple PropertyGroup additions.

However, making those changes doesn't seem like something LibGit2Sharp should be doing as part of installing the package.

@uluhonolulu I'll reply to the SO question with more details on the project changes you'd want to make.

**Comment by nulltoken** [comment] 2015-06-11 07:41
@bording Thanks a lot for having taken the time to investigate this! :heart_decoration: 

As this doesn't seem to be LibGit2Sharp related, closing this now.

Cheers!

**Closed by nulltoken** 2015-06-11 07:41 UTC

**Comment by uluhonolulu** [comment] 2015-06-13 18:40
Thanks!!!
