### ISSUE TITLE
Support for signed commits/tags

### ISSUE THREAD

**Issue by RockyTV** [libgit2/libgit2sharp#1309] opened 2016-04-23 20:42 UTC
Is it possible to implement PGP signing for tags and commits, as seen in this chapter of the Git book? https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

**Comment by carlosmn** [comment] 2016-04-26 19:48
Dupe of #1101. The commit support is incoming. The library has no special handling for tags, but extracting a tag signature is a split on the header line, which doesn't require library support.

**Closed by carlosmn** 2016-04-26 19:48 UTC
